
# default homepage
_welcome:
    path: /
    defaults: { _controller: SampleBundle:Default:index }

# module pages

sample:
    path:     /sample
    defaults: { _controller: SampleBundle:Default:index }

sample_module:
    path:     /sample/main-samples/{mode}/{extra}
    defaults: { _controller: SampleBundle:Default:mainsamples, mode:'default', extra:'default' }

sample_bootstrap:
    path:     /sample/bootstrap-samples
    defaults: { _controller: SampleBundle:Default:bootstrapsamples }

sample_json:
    path:     /sample/json/{mode}
    defaults: { _controller: SampleBundle:Default:json, mode:default }

benchmark:
    path:     /sample/benchmark
    defaults: { _controller: SampleBundle:Default:benchmark }

# end